#!/usr/bin/env bash
# docker run --rm -v $(pwd):/app nirname/documentary:latest $@
docker run --rm -it -v $(pwd):/app --entrypoint /bin/bash nirname/documentary:latest
echo "programming.technology" > ./docs/CNAME
